# .readthedocs.yml

version: 2

python:
  version: 3.7
  install:
    - requirements: requirements_dev.txt
    - method: pip
      path: .
      extra_requirements:
          - all
          - test

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true
