name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install libolm
      run: |
        wget http://archive.ubuntu.com/ubuntu/pool/universe/o/olm/libolm3_3.1.3+dfsg-2_amd64.deb
        sudo apt install libolm3_3.1.3+dfsg-2_amd64.deb
        wget http://archive.ubuntu.com/ubuntu/pool/universe/o/olm/libolm-dev_3.1.3+dfsg-2_amd64.deb
        sudo apt install libolm-dev_3.1.3+dfsg-2_amd64.deb
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -U tox tox-gh-actions
    - name: Run tests
      run: tox
    - name: Upload coverage report
      uses: codecov/codecov-action@v1
      with:
        file: ./cov.xml

  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: [docker, docs, lint]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install libolm
      run: |
        wget http://archive.ubuntu.com/ubuntu/pool/universe/o/olm/libolm3_3.1.3+dfsg-2_amd64.deb
        sudo apt install libolm3_3.1.3+dfsg-2_amd64.deb
        wget http://archive.ubuntu.com/ubuntu/pool/universe/o/olm/libolm-dev_3.1.3+dfsg-2_amd64.deb
        sudo apt install libolm-dev_3.1.3+dfsg-2_amd64.deb
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -U tox
    - name: Run checks
      run: tox -e ${{ matrix.component }}
